FORMAT: 1A
HOST: https://store-api.piflab.io/

# PIF Lab Store API

## Cart Collection [/cart]

### Get Cart API [GET/cart?{access_token}]
It retrieves Cart information, Access Token must be provided

+ Parameters
    + access_token: "hu7ljf7sg6tqmsfoj5xec8exfdqyh2zm" (required, string) - Acess Token of Cart to be returned

+ Response 401 (application/json)

        {
            "error": "Access Token is required"
        }

+ Response 401 (application/json)

        {
            "error": "Access Token is invalid"
        }

+ Response 401 (application/json)

        {
            "error": "Order is in processing state, please use another cart"
        }

+ Response 200 (application/json)

        {
            "items": [
                {
                    "id": 1,
                    "product_id": 1,
                    "name": "ABC",
                    "image_thumbnail_url": "https://piflab-store-mytest.s3-ap-southeast-1.amazonaws.com/products/2/thumbnail.1466244676.png",
                    "price": 10000,
                    "quantity": 1
                }
            ],
            "amounts": {
                "subtotal": 70000,
                "shipping": 0,
                "total": 70000
            },
            "access_token": "hu7ljf7sg6tqmsfoj5xec8exfdqyh2zm"
        }

### Create Cart API [PUT/cart]
It creates a cart

+ Request (application/x-www-form-urlencoded)

        product_id=1&quantity=1

+ Response 422 (application/json)

        {
            "error": "No Product selected"
        }

+ Response 422 (application/json)

        {
            "error": "No Quantity specified"
        }

+ Response 422 (application/json)

        {
            "error": "Quantity should not be 0"
        }

+ Response 201 (application/json)

        {
            "access_token": "hu7ljf7sg6tqmsfoj5xec8exfdqyh2zm",
            "items": [
                {
                    "id": 11,
                    "product_id": 1,
                    "name": "XBox",
                    "image_thumbnail_url": "https://piflab-store-mytest.s3-ap-southeast-1.amazonaws.com/products/2/thumbnail.1466244676.png",
                    "price": 70000,
                    "quantity": 1
                }
            ],
            "amounts": {
                "subtotal": 70000,
                "shipping": 0,
                "total": 70000
            }
        }

### Update Cart API [PUT/cart?{access_token}]
It updates a cart

+ Parameters
    + access_token: "hu7ljf7sg6tqmsfoj5xec8exfdqyh2zm" (required, string) - Acess Token of Cart to be updated

+ Request (application/x-www-form-urlencoded)

        product_id=2&quantity=1

+ Response 401 (application/json)

        {
            "error": "Access Token is required"
        }

+ Response 422 (application/json)

        {
            "error": "Access Token is invalid"
        }

+ Response 422 (application/json)

        {
            "error": "No Product selected"
        }

+ Response 422 (application/json)

        {
            "error": "No Quantity specified"
        }

+ Response 422 (application/json)

        {
            "error": "Quantity should not be 0"
        }

+ Response 422 (application/json)

        {
            "error": "Order is in processing state, please use another cart"
        }

+ Response 200 (application/json)

        {
            "items": [
                {
                    "id": 11,
                    "product_id": 1,
                    "name": "XBox",
                    "image_thumbnail_url": "https://piflab-store-mytest.s3-ap-southeast-1.amazonaws.com/products/2/thumbnail.1466244676.png",
                    "price": 70000,
                    "quantity": 1
                },
               {
                    "id": 12,
                    "product_id": 2,
                    "name": "PS3",
                    "image_thumbnail_url": "https://piflab-store-mytest.s3-ap-southeast-1.amazonaws.com/products/3/thumbnail.1466244676.png",
                    "price": 50000,
                    "quantity": 1
                }
            ],
            "amounts": {
                "subtotal": 120000,
                "shipping": 0,
                "total": 120000
            },
        }

### Update Cart Item API [PUT/cart/{item}?{access_token}]
It updates quantity of item in a cart

+ Parameters
    + item: `1` (number) - ID of Item to be updated
    + access_token: "hu7ljf7sg6tqmsfoj5xec8exfdqyh2zm" (string) - Acess Token of Cart to be updated

+ Request (application/x-www-form-urlencoded)

        quantity=2

+ Response 401 (application/json)

        {
            "error": "Access Token is required"
        }

+ Response 422 (application/json)

        {
            "error": "Access Token is invalid"
        }

+ Response 422 (application/json)

        {
            "error": "Item ID not found"
        }

+ Response 422 (application/json)

        {
            "error": "Quantity for item should bigger than 0"
        }

+ Response 422 (application/json)

        {
            "error": "Order is in processing state, please use another cart"
        }

+ Response 200 (application/json)

        {
            "items": [
                {
                    "id": 11,
                    "product_id": 1,
                    "name": "XBox",
                    "image_thumbnail_url": "https://piflab-store-mytest.s3-ap-southeast-1.amazonaws.com/products/2/thumbnail.1466244676.png",
                    "price": 70000,
                    "quantity": 2
                },
                {
                    "id": 12,
                    "product_id": 2,
                    "name": "PS3",
                    "image_thumbnail_url": "https://piflab-store-mytest.s3-ap-southeast-1.amazonaws.com/products/3/thumbnail.1466244676.png",
                    "price": 50000,
                    "quantity": 1
                }
            ],
            "amounts": {
                "subtotal": 190000,
                "shipping": 0,
                "total": 120000
            },
        }

### Delete Cart Item API [DELETE/cart/item/{id}?{access_token}]
It deletes a item in a cart

+ Parameters
    + id: `1` (number) - ID of Item to be updated
    + access_token: "hu7ljf7sg6tqmsfoj5xec8exfdqyh2zm" (string) - Acess Token of Cart to be updated

+ Response 422 (application/json)

        {
            "error": "Access Token is invalid"
        }

+ Response 404 (application/json)

        {
            "error": "Not found Item Id in a Cart"
        }

+ Response 401 (application/json)

        {
            "error": "Access Token is required"
        }

+ Response 200 (application/json)

        {

        }

### Checkout API [POST/cart/checkout?{access_token}]
It checkouts a cart

+ Parameters
    + access_token: hu7ljf7sg6tqmsfoj5xec8exfdqyh2zm (required, string) - Access Token of Cart to be updated

+ Request (application/x-www-form-urlencoded)

        name=Tran%20Van%20A&adress=Ho%20Chi%20Minh%20City&phone=01679931234&email=tranvana@abc.com

+ Request (application/json)

        {
            "name": "Tran Van A",
            "address": "Ho Chi Minh City",
            "phone": "01679931234",
            "email": "tranvana@abc.com",
            "note": "Some optional note"
        }

+ Response 422 (application/json)

        {
            "error": "Order is in processing state, please use another cart"
        }

+ Response 422 (application/json)

        {
            "error": "Access Token is invalid"
        }

+ Response 401 (application/json)

        {
            "error": "Access Token is required"
        }

+ Response 401 (application/json)

        {
            "error": "Customer's Name is required"
        }

+ Response 401 (application/json)

        {
            "error": "Customer's Address is required"
        }

+ Response 401 (application/json)

        {
            "error": "Customer's Phone number is required"
        }

+ Response 401 (application/json)

        {
            "error": "Customer's Email is required"
        }

+ Response 401 (application/json)

        {
            "error": "Customer's Email address is invalid"
        }

+ Response 200 (application/json)

        {
            "id": "71pokfvao3ix8i39ia8xv0qjpwwkh6rt"
            "items": [
                {
                    "id": 129,
                    "product_id": 1,
                    "name": "XBox",
                    "image_thumbnail_url": "https://piflab-store.s3-ap-southeast-1.amazonaws.com/products/1/image_thumbnail_1471330683.png?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIAJNLAZER4FCA65TWA%2F20160926%2Fap-southeast-1%2Fs3%2Faws4_request&X-Amz-Date=20160926T090822Z&X-Amz-Expires=900&X-Amz-SignedHeaders=host&X-Amz-Signature=eccbef044bcae3447aa5be8e0538966262b9a9607cf6b0b5ffa953c8fa207945",
                    "price": 70000,
                    "quantity": 1
                }
            ],
            "amounts": {
                "subtotal": 70000,
                "shipping": 0,
                "total": 70000
            },
            "customer": {
                "id": "71pokfvao3ix8i39ia8xv0qjpwwkh6rt",
                "name": "Tran Van A",
                "address": "Ho Chi Minh city",
                "phone": "01679931234",
                "email": "tranvana@abc.com",
                "note": "Some optional note"
            },
            "status": "processing",
            "created_at": "2016-09-26T09:08:18.429532Z",
            "updated_at": "2016-09-26T09:08:22.694556863Z"
        }

## Order Collection [/orders]

### Get Orders API [GET/orders]
It returns lists of Order

+ Attributes
    + offset: `0` (number) - The list of results start from index's value of `offset`
    + limit: `1` (number) - The maximum number off results returned
    + q: `An` (string) - The customer's name to search
    + sort: `created_at|asc` (string) - Sort field with method, support method: `desc`, `asc`, fields: `created_at`, `upated_at`, `id`

+ Response 422 (application/json)

        {
            "error": "Only support processing/shipping/completed/cancelled in status field"
        }

+ Response 422 (application/json)

        {
            "error": "Only support created_at/updated_at/id in sort field"
        }

+ Response 422 (application/json)

        {
            "error": "Only support desc/asc in sort field"
        }

+ Response 422 (application/json)

        {
            "error": "Invalid sort field format, should be: create_at/updated_at/id|desc/asc"
        }

+ Response 200 (application/json)

        {
            "data": [
                {
                    "id": "rvd2e1nm4re8uhmhh60zb2t616yl323o",
                    "items": [
                        {
                            "id": 116,
                            "product_id": 1,
                            "name": "Output Viewer",
                            "image_thumbnail_url": "https://piflab-store-mytest.s3-ap-southeast-1.amazonaws.com/products/1/image_thumbnail_1473315177.png?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIAIKCGLONYH2QY5BUA%2F20160929%2Fap-southeast-1%2Fs3%2Faws4_request&X-Amz-Date=20160929T040222Z&X-Amz-Expires=900&X-Amz-SignedHeaders=host&X-Amz-Signature=ce0cde23ed3b7005131e2b18e8f9d62b0f5995c15b9e8f6feb2c75bd6a27518c",
                            "price": 55644,
                            "quantity": 1
                        }
                    ],
                    "amounts": {
                        "subtotal": 55644,
                        "shipping": 0,
                        "total": 55644
                    },
                    "customer": {
                        "id": "rvd2e1nm4re8uhmhh60zb2t616yl323o",
                        "name": "Tran Van A",
                        "address": "Ho Chi Minh city",
                        "phone": "01679936867",
                        "email": "tran_van_a@gmail.com",
                        "note": "some optional note here"
                    },
                    "status": "shipping",
                    "created_at": "2016-09-25T02:40:47.569511Z",
                    "updated_at": "2016-09-25T02:40:56.567307Z"
                }
            ],
            "paging": {
                "next": "/orders?offset=1&limit=1&id|desc",
                "previous": null
            }
        }

### Get Order detail API [GET/orders/{id}]
It returns detail of Order

+ Parameters
    + id: a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11 (required, string) - ID of Order
+ Response 404 (application/json)

        {
            "error": "Record not found"
        }

+ Response 200 (application/json)

        {
            "id": "a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11",
            "items": [
                {
                    "id": 11,
                    "product_id": 1,
                    "name": "XBox",
                    "image_thumbnail_url": "https://piflab-store-mytest.s3-ap-southeast-1.amazonaws.com/products/2/thumbnail.1466244676.png",
                    "price": 70000,
                    "quantity": 2
                },
                {
                    "id": 12,
                    "product_id": 2,
                    "name": "PS3",
                    "image_thumbnail_url": "https://piflab-store-mytest.s3-ap-southeast-1.amazonaws.com/products/3/thumbnail.1466244676.png",
                    "price": 50000,
                    "quantity": 1
                }
            ],
            "amounts": {
                "subtotal": 190000,
                "shipping": 0,
                "total": 120000
            },
            "customer": {
                "id": "a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11",
                "name": "Tran Van A",
                "address": "Ho Chi Minh City",
                "phone": "01679931234",
                "email": "tranvana@abc.com",
                "note": "Some optional note"
            },
            "status": "processing",
            "created_at": "2016-06-18T10:11:16.144073Z",
            "updated_at": "2016-06-18T11:24:01.917424Z"
        }

## Products Collection [/products]

### Get Products API [GET]
It lists products by pages, if the `offset`/`limit` parameters is not valid, it list at least 10 products, at zero `offset`

+ Attributes
    + offset: `0` (number) - The list of results start from index's value of `offset`
    + limit: `1` (number) - The maximum number off results returned
    + q: `An` (string) - The product's name to search

+ Response 200 (application/json)

        {
            "data": [
                {
                    "id": 2,
                    "name": "product",
                    "price": 12500,
                    "provider": "Microsoft",
                    "rating": 4,
                    "status": "sale",
                    "detail": "some text",
                    "image_url": "https://piflab-store-mytest.s3-ap-southeast-1.amazonaws.com/products/2/origin.14662446.png",
                    "image_thumbnail_url": "https://piflab-store-mytest.s3-ap-southeast-1.amazonaws.com/products/2/thumbnail.1466244676.png",
                    "image_detail_url": "https://piflab-store-mytest.s3-ap-southeast-1.amazonaws.com/products/2/detail.1466244676.png",
                    "created_at": "2016-06-18T10:11:16.144073Z",
                    "updated_at": "2016-06-18T11:24:01.917424Z"
                },
                {
                    "id": 1,
                    "name": "product",
                    "price": 22,
                    "provider": "Microsoft",
                    "rating": 4,
                    "status": "sale",
                    "detail": "some text",
                    "image_url": "https://piflab-store-mytest.s3-ap-southeast-1.amazonaws.com/products/1/origin.1466244681.png",
                    "image_thumbnail_url": "https://piflab-store-mytest.s3-ap-southeast-1.amazonaws.com/products/1/thumbnail.1466244681.png",
                    "image_detail_url": "https://piflab-store-mytest.s3-ap-southeast-1.amazonaws.com/products/1/detail.1466244681.png",
                    "created_at": "2016-06-18T10:11:21.985591Z",
                    "updated_at": "2016-06-18T11:38:21.83933Z"
                },
                {
                    "id": 0,
                    "name": "product",
                    "price": 22,
                    "provider": "Microsoft",
                    "rating": 4,
                    "status": "sale",
                    "detail": "some text",
                    "image_url": "https://piflab-store-mytest.s3-ap-southeast-1.amazonaws.com/products/0/origin.1466244681.png",
                    "image_thumbnail_url": "https://piflab-store-mytest.s3-ap-southeast-1.amazonaws.com/products/0/thumbnail.1466244681.png",
                    "image_detail_url": "https://piflab-store-mytest.s3-ap-southeast-1.amazonaws.com/products/0/detail.1466244681.png",
                    "created_at": "2016-06-18T10:11:21.985591Z",
                    "updated_at": "2016-06-18T11:38:21.83933Z"
                }
            ],
            "paging": {
                "next": null,
                "previous": "/products/offset=0&limit=10"
            }
        }

### Get Product details API [GET/products/{id}]
It returns details of a product

+ Parameters
    + id: 1 (integer) - Id of a product to get details from

+ Response 404 (application/json)

    + Body

            {
                "error": "Record not found"
            }

+ Response 200 (application/json)

    + Body

            {
                "id": 1,
                "name": "XBox",
                "price": 70000,
                "provider": "Microsoft",
                "rating": 3.5,
                "status": "sale",
                "detail": "rerum itaque cumque explicabo omnis."
                "image_url": "https://piflab-store.s3-ap-southeast-1.amazonaws.com/products/1/origin.png",
                "image_thumbnail_url": "https://piflab-store.s3-ap-southeast-1.amazonaws.com/products/1/thumbnail.png",
                "image_detail_url": "https://piflab-store.s3-ap-southeast-1.amazonaws.com/products/1/detail.png",
                "created_at": "2016-01-17T07:20:40+0000",
                "updated_at": "2016-01-17T07:20:40+0000",
            }

### Create Product API [POST]
It creates a product

+ Request (application/json)

        {
            "name": "XBox",
            "price": 70000,
            "provider": "Microsoft",
            "rating": 3.5,
            "status": "sale",
            "detail": "some detail of product"
        }

+ Request (application/x-www-form-urlencoded)

        name=XBox&price=70000&provider=Microsoft&rating=3.5&status=sale&detail=some%20detail%20of%20product

+ Request (multipart/form-data; boundary=---BOUNDARY)

        -----BOUNDARY
        Content-Disposition: form-data; name="image"; filename="image.jpg"
        Content-Type: image/jpeg
        Content-Transfer-Encoding: base64

        /9j/4AAQSkZJRgABAQEAYABgAAD/2wBDAAgGBgcGBQgHBwcJCQgKDBQNDAsLDBkSEw8UHRofHh0a
        HBwgJC4nICIsIxwcKDcpLDAxNDQ0Hyc5PTgyPC4zNDL/2wBDAQkJCQwLDBgNDRgyIRwhMjIyMjIy
        MjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjL/wAARCAABAAEDASIA
        AhEBAxEB/8QAFQABAQAAAAAAAAAAAAAAAAAAAAf/xAAUEAEAAAAAAAAAAAAAAAAAAAAA/8QAFAEB
        AAAAAAAAAAAAAAAAAAAAAP/EABQRAQAAAAAAAAAAAAAAAAAAAAD/2gAMAwEAAhEDEQA/AL+AD//Z
        -----BOUNDARY

+ Response 422 (application/json)

    + Body

            {
                "error": "Image is required"
            }

+ Response 201 (application/json)

    + Body

            {
                "id": 1,
                "name": "XBox",
                "price": 70000,
                "provider": "Microsoft",
                "rating": 3,
                "status": "sale",
                "detail": "rerum itaque cumque explicabo omnis."
                "image_url": "https://piflab-store.s3-ap-southeast-1.amazonaws.com/products/1/origin.png",
                "image_thumbnail_url": "https://piflab-store.s3-ap-southeast-1.amazonaws.com/products/1/thumbnail.png",
                "image_detail_url": "https://piflab-store.s3-ap-southeast-1.amazonaws.com/products/1/detail.png",
                "created_at": "2016-01-17T07:20:40+0000",
                "updated_at": "2016-01-17T07:20:40+0000",
            }

### Update Products API [PUT/products/{id}]
It updates a product

+ Request (application/json)

        {
            "rating": 5.1,
        }

+ Request (application/x-www-form-urlencoded)

        rating=5.1

+ Request (multipart/form-data; boundary=---BOUNDARY)

        ------WebKitFormBoundaryXBSDgs8T1omqCUw9
        Content-Disposition: form-data; name="rating"

        5.1
        ------WebKitFormBoundaryXBSDgs8T1omqCUw9--

+ Response 422 (application/json)

    + Body

            {
                "error": "Rating must be less than or equal to 5"
            }

+ Response 200 (application/json)

    + Body

            {
                "id": 1,
                "name": "XBox",
                "price": 70000,
                "provider": "Microsoft",
                "rating": 3.5,
                "status": "sale",
                "detail": "rerum itaque cumque explicabo omnis."
                "image_url": "https://piflab-store.s3-ap-southeast-1.amazonaws.com/products/1/origin.png",
                "image_thumbnail_url": "https://piflab-store.s3-ap-southeast-1.amazonaws.com/products/1/thumbnail.png",
                "image_detail_url": "https://piflab-store.s3-ap-southeast-1.amazonaws.com/products/1/detail.png",
                "created_at": "2016-01-17T07:20:40+0000",
                "updated_at": "2016-01-17T07:20:40+0000",
            }

### Delete Products API [DELETE/products/{id}]
It deletes a product

+ Response 200 (application/json)

    + Body

            {
                "id": 1,
                "name": "XBox",
                "price": 70000,
                "provider": "Microsoft",
                "rating": 3.5,
                "status": "sale",
                "detail": "rerum itaque cumque explicabo omnis."
                "image_url": "https://piflab-store.s3-ap-southeast-1.amazonaws.com/products/1/origin.png",
                "image_thumbnail_url": "https://piflab-store.s3-ap-southeast-1.amazonaws.com/products/1/thumbnail.png",
                "image_detail_url": "https://piflab-store.s3-ap-southeast-1.amazonaws.com/products/1/detail.png",
                "created_at": "2016-01-17T07:20:40+0000",
                "updated_at": "2016-01-17T07:20:40+0000",
            }
